services:
  - type: web
    name: eurusd-data-pipeline
    env: python
    buildCommand: ./build.sh
    startCommand: bash start.sh

  - type: cron
    name: eurusd-update-cron
    env: python
    schedule: "*/15 * * * *"
    buildCommand: ./build.sh
    startCommand: python data_hora.py